// Keep animation curve consistent across the whole scene
export const EASE = [0.19, 1, 0.22, 1]

// Dev fallback (only used if CMS returns nothing)
export const FALLBACK_HOTSPOTS = [
  {
    id: 'spot-1',
    label: 'Forest',
    x: 30,
    y: 25,
    hotspotIdleSrc: null,
    buildingLoopSrc: null,
    buildingSpawnSrc: null,
    hotspotIdleW: 96,
    hotspotIdleH: 96,
    buildingW: 220,
    buildingH: 220,
    anchorX: 50,
    anchorY: 92,
    spawnDurationMs: 1400,
  },
  {
    id: 'spot-2',
    label: 'Cave',
    x: 22,
    y: 62,
    hotspotIdleSrc: null,
    buildingLoopSrc: null,
    buildingSpawnSrc: null,
    hotspotIdleW: 96,
    hotspotIdleH: 96,
    buildingW: 220,
    buildingH: 220,
    anchorX: 50,
    anchorY: 92,
    spawnDurationMs: 1400,
  },
  {
    id: 'spot-3',
    label: 'Lab',
    x: 78,
    y: 30,
    hotspotIdleSrc: null,
    buildingLoopSrc: null,
    buildingSpawnSrc: null,
    hotspotIdleW: 96,
    hotspotIdleH: 96,
    buildingW: 220,
    buildingH: 220,
    anchorX: 50,
    anchorY: 92,
    spawnDurationMs: 1400,
  },
]
