/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'scene-hotspots': SceneHotspot;
    projects: Project;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'scene-hotspots': SceneHotspotsSelect<false> | SceneHotspotsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'player-selection': PlayerSelection;
    islandBootDock: IslandBootDock;
    islandScene: IslandScene;
    'home-dock': HomeDock;
    'about-us': AboutUs;
  };
  globalsSelect: {
    'player-selection': PlayerSelectionSelect<false> | PlayerSelectionSelect<true>;
    islandBootDock: IslandBootDockSelect<false> | IslandBootDockSelect<true>;
    islandScene: IslandSceneSelect<false> | IslandSceneSelect<true>;
    'home-dock': HomeDockSelect<false> | HomeDockSelect<true>;
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scene-hotspots".
 */
export interface SceneHotspot {
  id: string;
  /**
   * Hover works on desktop only. Mobile will still use tap.
   */
  trigger?: ('click' | 'hover') | null;
  name: string;
  x: number;
  y: number;
  anchorX?: number | null;
  anchorY?: number | null;
  buildingW?: number | null;
  buildingH?: number | null;
  hotspotIdle?: (string | null) | Media;
  buildingSpawn?: (string | null) | Media;
  buildingLoop?: (string | null) | Media;
  /**
   * How long the building spawn animation lasts (milliseconds).
   */
  spawnDurationMs?: number | null;
  projects?: (string | Project)[] | null;
  introEnabled?: boolean | null;
  introPages?:
    | {
        title: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  order?: number | null;
  projectName: string;
  subTitle: string;
  client: string;
  type?: {
    text?: string | null;
    icon?: {
      icon1?: (string | null) | Media;
      icon2?: (string | null) | Media;
    };
  };
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  achievement?: string | null;
  /**
   * Short intro sentence shown in the project panel / popup before opening the details page.
   */
  panelIntro: string;
  singleImage: string | Media;
  ctaLabel?: string | null;
  ctaType?: ('route' | 'external') | null;
  ctaUrl?: string | null;
  /**
   * Auto-generated from project name.
   */
  slug?: string | null;
  technologies?:
    | {
        image?: (string | null) | Media;
        name?: string | null;
        semiLarge?: boolean | null;
        id?: string | null;
      }[]
    | null;
  carousel?: {
    images?:
      | {
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  googlePlayUrl?: {
    img?: (string | null) | Media;
    url?: string | null;
  };
  appStoreUrl?: {
    img?: (string | null) | Media;
    url?: string | null;
  };
  url?: string | null;
  urlGroup?:
    | {
        url?: string | null;
        name?: string | null;
        btnText?: string | null;
        id?: string | null;
      }[]
    | null;
  comingSoon?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: string;
  source?: string | null;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  userAgent?: string | null;
  pageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'scene-hotspots';
        value: string | SceneHotspot;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: string | ContactMessage;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scene-hotspots_select".
 */
export interface SceneHotspotsSelect<T extends boolean = true> {
  trigger?: T;
  name?: T;
  x?: T;
  y?: T;
  anchorX?: T;
  anchorY?: T;
  buildingW?: T;
  buildingH?: T;
  hotspotIdle?: T;
  buildingSpawn?: T;
  buildingLoop?: T;
  spawnDurationMs?: T;
  projects?: T;
  introEnabled?: T;
  introPages?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  projectName?: T;
  subTitle?: T;
  client?: T;
  type?:
    | T
    | {
        text?: T;
        icon?:
          | T
          | {
              icon1?: T;
              icon2?: T;
            };
      };
  challenge?: T;
  coverage?: T;
  descriptions?: T;
  achievement?: T;
  panelIntro?: T;
  singleImage?: T;
  ctaLabel?: T;
  ctaType?: T;
  ctaUrl?: T;
  slug?: T;
  technologies?:
    | T
    | {
        image?: T;
        name?: T;
        semiLarge?: T;
        id?: T;
      };
  carousel?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  googlePlayUrl?:
    | T
    | {
        img?: T;
        url?: T;
      };
  appStoreUrl?:
    | T
    | {
        img?: T;
        url?: T;
      };
  url?: T;
  urlGroup?:
    | T
    | {
        url?: T;
        name?: T;
        btnText?: T;
        id?: T;
      };
  comingSoon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  source?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  userAgent?: T;
  pageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-selection".
 */
export interface PlayerSelection {
  id: string;
  enabled?: boolean | null;
  title?: string | null;
  players?:
    | {
        id: string;
        name: string;
        badgeLabel?: string | null;
        description?: string | null;
        avatarImage?: (string | null) | Media;
        order?: number | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islandBootDock".
 */
export interface IslandBootDock {
  id: string;
  enabled?: boolean | null;
  title: string;
  pages: {
    text: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islandScene".
 */
export interface IslandScene {
  id: string;
  background?: (string | null) | Media;
  maxZoomMult?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-dock".
 */
export interface HomeDock {
  id: string;
  enabled?: boolean | null;
  showOnlyOnHome?: boolean | null;
  launcher?: {
    position?: ('bottom-left' | 'bottom-right') | null;
    offsetX?: number | null;
    offsetY?: number | null;
  };
  assets?: {
    openGif?: (string | null) | Media;
    staticPhone?: (string | null) | Media;
  };
  timing?: {
    spawnMs?: number | null;
  };
  ui?: {
    animateIconsOnOpen?: boolean | null;
    iconsStaggerMs?: number | null;
  };
  screens?:
    | {
        key: string;
        title: string;
        icon?: (string | null) | Media;
        type: 'messageForm' | 'locationsList' | 'phonesList';
        message?: {
          submitLabel?: string | null;
          successText?: string | null;
          recipientEmail?: string | null;
        };
        locations?:
          | {
              title: string;
              address: string;
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        phones?:
          | {
              label: string;
              phone: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        order?: number | null;
        label: string;
        icon?: (string | null) | Media;
        slot: 'top' | 'bottom';
        type: 'internal' | 'route' | 'external';
        screenKey?: string | null;
        routePath?: string | null;
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: string;
  /**
   * Where the back button navigates (e.g. /).
   */
  backHref: string;
  backButtonImage: string | Media;
  companyLabel: string;
  missionText: string;
  teamTitle: string;
  /**
   * Must match one of members[].key (e.g. mustafa).
   */
  defaultMemberKey: string;
  members: {
    key: string;
    name: string;
    avatarStatic: string | Media;
    avatarAnimated: string | Media;
    realPhoto?: (string | null) | Media;
    bioText: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-selection_select".
 */
export interface PlayerSelectionSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  players?:
    | T
    | {
        id?: T;
        name?: T;
        badgeLabel?: T;
        description?: T;
        avatarImage?: T;
        order?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islandBootDock_select".
 */
export interface IslandBootDockSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  pages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islandScene_select".
 */
export interface IslandSceneSelect<T extends boolean = true> {
  background?: T;
  maxZoomMult?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-dock_select".
 */
export interface HomeDockSelect<T extends boolean = true> {
  enabled?: T;
  showOnlyOnHome?: T;
  launcher?:
    | T
    | {
        position?: T;
        offsetX?: T;
        offsetY?: T;
      };
  assets?:
    | T
    | {
        openGif?: T;
        staticPhone?: T;
      };
  timing?:
    | T
    | {
        spawnMs?: T;
      };
  ui?:
    | T
    | {
        animateIconsOnOpen?: T;
        iconsStaggerMs?: T;
      };
  screens?:
    | T
    | {
        key?: T;
        title?: T;
        icon?: T;
        type?: T;
        message?:
          | T
          | {
              submitLabel?: T;
              successText?: T;
              recipientEmail?: T;
            };
        locations?:
          | T
          | {
              title?: T;
              address?: T;
              highlight?: T;
              id?: T;
            };
        phones?:
          | T
          | {
              label?: T;
              phone?: T;
              id?: T;
            };
        id?: T;
      };
  items?:
    | T
    | {
        order?: T;
        label?: T;
        icon?: T;
        slot?: T;
        type?: T;
        screenKey?: T;
        routePath?: T;
        externalUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  backHref?: T;
  backButtonImage?: T;
  companyLabel?: T;
  missionText?: T;
  teamTitle?: T;
  defaultMemberKey?: T;
  members?:
    | T
    | {
        key?: T;
        name?: T;
        avatarStatic?: T;
        avatarAnimated?: T;
        realPhoto?: T;
        bioText?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}